import type { PricingLevelKey } from "./types/index";
export declare const BUSINESS_NAME = "Jikstel NG";
export declare const TEL_PRO_BUNDLE = "bundle";
export declare const TEL_PRO_AIRTIME = "airtime";
export declare const TEL_PRO_BCOUPON = "coupon";
export declare const TEL_PRO_RCOUPON = "recharge";
export declare const TEL_PRODUCTS: string[];
export declare const TEL_COM_NAMES: string[];
export declare const TEL_COM_CODES: string[];
export declare const TEL_COM_ZONES: string[];
export declare const TEL_ZON_NAMES: string[];
export declare const TEL_DATA_TYPES: string[];
export declare const TEL_DATA_NAMES: string[];
export declare const TEL_TOPUP_TYPES: string[];
export declare const TEL_TOPUP_NAMES: string[];
export declare const TEL_DATA_ENUMS: Record<string, string>;
export declare const TEL_TOPUP_ENUMS: Record<string, string>;
export declare const PRICING_LEVELS: PricingLevelKey[];
export declare const CAT_EDU_STUFF = "edustuff";
export declare const EDUSTUFF_CODES: string[];
export declare const SSCEEXAM_CODES: string[];
export declare const SSCEEXAM_NAMES: string[];
export declare const BILLPAY_CODES: string[];
export declare const CAT_CABLE_PLAN = "cableplan";
export declare const CABLETV_CODES: string[];
export declare const CAT_DISCO_PLAN = "discosubs";
export declare const PAYMENT_CHANNELS: string[];
export declare const PAYMENT_CH_NAMES: string[];
export declare const PAYMENT_SERVICES: string[];
export declare const MESSAGE_CHANNELS: string[];
declare const _default: {
    BUSINESS_NAME: string;
    TEL_PRO_BUNDLE: string;
    TEL_PRO_AIRTIME: string;
    TEL_PRO_BCOUPON: string;
    TEL_PRO_RCOUPON: string;
    TEL_PRODUCTS: string[];
    TEL_COM_NAMES: string[];
    TEL_COM_CODES: string[];
    TEL_ZON_NAMES: string[];
    TEL_DATA_TYPES: string[];
    TEL_DATA_NAMES: string[];
    TEL_TOPUP_TYPES: string[];
    TEL_TOPUP_NAMES: string[];
    TEL_DATA_ENUMS: Record<string, string>;
    TEL_TOPUP_ENUMS: Record<string, string>;
    PRICING_LEVELS: PricingLevelKey[];
    EDUSTUFF_CODES: string[];
    SSCEEXAM_CODES: string[];
    SSCEEXAM_NAMES: string[];
    BILLPAY_CODES: string[];
    CABLETV_CODES: string[];
    PAYMENT_CH_NAMES: string[];
    PAYMENT_CHANNELS: string[];
    MESSAGE_CHANNELS: string[];
};
export default _default;
